// <auto-generated />
namespace HRMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HRMSDbConnection23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HRMSDbConnection23));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201247132_HRMSDbConnection23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
